src/app/frontend/views/events-view/events-view.component.html
src/app/frontend/views/events-view/events-view.component.ts

@SmallhillCZ vsiml jsem si že ve view programu jsou linky na google dokumenty hardcoded. Pokusil jsem se zmenit na věci z konfigu, koukni jestli jsem to neudelal uplne blbe :)

Change hardcoded Troja GDocs links to variables from WebConfig

---

client/src/app/frontend/views/events-view/events-view.component.html

Narychlo udělaná sekce do programu pro Pata na nové kajakářské tréninky na BO. Později přidám alespoň nějakou fotku až bude.
Chtělo by to dát odkazy na formulář a obsazenost někam do administrace, ale nemám kapacitu na to zjišťovat co vše se musí měnit. Musíš mi to někdy ukázat :).

Add kayak trainings at Bosan as last section of events

---

server/src/config/acl.js
server/src/controllers/photos.js

TODO is to show only published photos. Or make separate public API without authentication.

Hotfix for photos not displaying on frontend

---

server/src/controllers/login/create-token.js
server/src/controllers/login/login-user.js
server/src/controllers/users.js

Nový uživatel se vytvoří, ale nastane chyba při vygenerování tokenu, co se má zaslat na mail. Kvůli tomu to vypadá, že se uživatel nevytvořil. Při druhém pokusu pak už je zas chyba, že uživatel existuje.
Chyba byla v chybějící závislosti... javascript 🤦‍♀️, už aby to bylo v typescriptu.

Oprava chyby při vytvoření nového uživatele

---

server/src/controllers/albums.js

Ještě se budou muset opravit všechny historický alba, kterým chybí datePublished.

Oprava zobrazování alba v sekci aktuálně, closes #312

---

.github/workflows/test-build-client-admin.yml
.github/workflows/test-build-client.yml
.github/workflows/test-build-server.yml

Když se pushne do větve test, tak se buildne docker image a nahraje se na dockerhub s tagem test

Build z větve test do docker image labelu test

---

server/Dockerfile
server/package-lock.json
server/package.json
server/src/config/server.js
server/src/controllers/photos.js

Tahle změna není nijak viditelná, jen ulehčí našemu serveru. Balík serveru už nebude mít 1,1 GB, ale jen 250 MB.
Dalo by se pokročit ještě daleko dál, spousta z instalovaných NPM balíčků se nepoužije. K tomu by se musel použít tree shaking (odebrání nepoužitého kódu) pomocí např. webpacku.
- V Dockerfile se image netvoří z `node:14.16` ale z `node:14.16-alpine`
- Balíčky se nově instalují pomocí `npm ci --production`.
- Balíček `cors` zahrnut v dependencies, aby byl součástí instalace.
- Opraven chybný HTTP status 500 při nenalezeném souboru fotografie, nyní vrací správně 404.
Nemáme žádnou novou funkci, takže cílem je otestovat, jestli se nic nerozbilo.
1. Přihlásit se na `test.bosan.cz`, obnovit přes CTRL+F5
2. Proklikat web, vytvořit akci, album atd.
3. Napsat feedback, buď `Approve …

Serverový docker image založený na Apline Linux verzi NodeJS image

---

client/src/app/components/page-footer/page-footer.component.html

Smyslem této změny je ...
Do patičky webu jsem přidala link na instagram.
- 
Jít do patičky webu a zjistit, zda to přesměruje na náš instagram.

Add instagram link

---

client-admin/src/app/core/core.module.ts

Smyslem této změny je nastavit text u tlačítka zpět na iOS zařízeních na české "Zpět". U ostatních zařízení ponechat šipku bez textu.
- natvrdo nastavený text pro Ionic back button (per platform - jen pro iOS, ostatní bez textu)

Fix ion back button text language

---

client-admin/src/app/shared/components/event-calendar/event-calendar.component.html
client-admin/src/app/shared/components/event-calendar/event-calendar.component.ts

Smyslem této změny je zvýraznění aktuálního dne v kalendáři pro snadnější orientaci.
- přidána funkce isToday a vlastnost today v CalendarDayProperties interface
- v html přidána podmínka a v případě dnešního dne se datum zobrazí uvnitř ion badge elementu

Current day highlighted using ion-badge. Fixes #375

---

client/src/app/views/camp-view/camp-view.component.html

- změna ceny pro tábor 2021 
1. Otevřit stránku tábor, podívat se jestli je cena ve znění: 
>  Tábory v roce 2021 jsou pro přihlášené dětské účastníky zdarma a poplatek bude hrazen z dotace poskytnuté MŠMT.

Change price of camp in 2021

---

client-admin/package-lock.json
client-admin/package.json
client-admin/src/app/shared/components/action-buttons/action-buttons.component.html
client-admin/src/app/shared/components/action-buttons/action-buttons.component.ts

-  oprava chybějícího tlačítka vést akci

oprava chybějícího tlačítka vést akci

---

client-admin/package-lock.json
client-admin/package.json
client-admin/src/app/modules/events/views/events-view/events-view-info/events-view-info.component.ts

- Nezobrazovat modal pro poznámku když je to z "Vést akci"

Nezobrazovat modal pro poznámku když je to z "Vést akci"

---

client-admin/package-lock.json
client-admin/package.json
client-admin/src/app/modules/albums/views/albums-view/albums-view-photos/albums-view-photos.component.html
client-admin/src/app/schema/photo.ts
server/src/config/server.js
server/src/controllers/albums.js
server/src/controllers/albums/photo-save.js
server/src/controllers/photos.js
server/src/models/photo.js

Smyslem této změny je mít přehled, kdo mi nahrál fotky do alba.
Pomůže taky později k filtrování dle #403
- u každé fotky se uloží, kdo ji nahrál, a následně se to zobrazí v seznamu fotek
1. Otevřít si http://test.bosan.cz, zkontrolovat, že verze je 3.0.9
2. Nahrát fotku do nějakého alba
3. Zkontrolovat, jestli je moje přezdívka/login uvedena v seznamu fotek u dané fotky. Týká se pouze nových fotek.
4. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

Zobrazovat, kdo nahrál jaké fotky do alba

---

server/package-lock.json
server/package.json
server/src/controllers/events-event-registration.js

Smyslem této změny je opravit nahrání přihlášky
1. Otevřít si test.bosan.cz a přihlásit se testovacím účtem
2. Zkusit nahrát a zobrazit přihlášku u akce.
3. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

Fix registration upload/download

---

client/src/app/app.component.scss
client/src/app/components/page-menu/page-menu.component.scss

Smyslem této změny je ...
- 
Cílem je ...
1.
X. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

Menu repair

---

client-admin/.gitignore
client-admin/package-lock.json
client-admin/package.json
client-admin/src/app/modules/albums/components/photo-view/photo-view.component.ts
client-admin/src/app/modules/albums/views/albums-view/albums-view-photos/albums-view-photos.component.ts

- oprava kolize funkcí šipek při popisování fotek
0. Otevřít si interní testovací sekci na https://test.bosan.cz/ a zkontrolovat, že verze je 3.0.14
1. Otevřít si fotku ve fotkách
2. Otevřít si editaci popisku
3. Zkusit zmáčknout šipky vlevo a vpravo - měly by jen posouvat kurzorem
4. Zkusit zmáčknout Escape, měl by jen zrušit editaci popisku
5. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

Oprava kolize funkcí šipek při popisování fotek

---

interni/package-lock.json
interni/package.json
interni/src/app/modules/members/views/members-list/members-list.component.html
interni/src/app/modules/members/views/members-list/members-list.component.scss
interni/src/app/modules/members/views/members-list/members-list.component.ts

- na mobilu se databáze zobrazí jako seznam místo tabulky
- na počítači je možnost zkopírovat řádek do schránky (a pak třeba do excelu)
1. Otevřít interni.test.bosan.cz a zkontrolovat, že mám verzi 3.2.0
2. Proklikat databázi, ověřit, že se na mobilu načte seznam a na počítači tabulka
3. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

Responzivní seznam členů

---

web/src/app/app.component.html
web/src/app/app.module.ts
web/src/app/components/ukraine-help/ukraine-help.component.html
web/src/app/components/ukraine-help/ukraine-help.component.scss
web/src/app/components/ukraine-help/ukraine-help.component.ts

@elenfant souhlasíš?
Nahoru to dáš jednoduše nešlo. Po kliknutí se otevře https://www.stojimezaukrajinou.cz/

Odkaz na stojimezaukrajinou.cz kde je rozcestník jak pomáhat

---

interni/package-lock.json
interni/package.json
interni/src/app/modules/events/views/events-list/events-list.component.ts
interni/src/app/modules/events/views/events-view/events-view-info/events-view-info.component.ts
interni/src/app/modules/program/views/program-calendar/program-calendar.component.ts
interni/src/app/modules/program/views/program-planning/program-planning.component.ts

- oprava smazání akce
1. Otevři si interni.test.bosan.cz a zkontroluj, že verze je 3.2.4
2. Vytvoř akci a zkus, jestli jí lze smazat a nedějou se u toho jiný divný věci.
3. Napiš feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

Oprava nefunkčního smazání akce

---

web/src/app/views/camp-view/camp-view.component.html
web/src/app/views/events-view/events-view.component.html

- změna adresy loděnice a tréninků v loděnici v sekci Program - ideálně mergnout po schůzce 14. 9. 2022
1. Otevři sekci program a ověř že adrease loděnice je V náklích 445/1a, Praha 4, 147 00

Change Bosan address

---

web/src/app/components/page-footer/page-footer.component.html

- přidána datová schránka do kontaktů

Datová schránka do kontaktů

---

web/src/app/app.component.html

- Odebrán banner k Ukrajině
1. Otevři si test.bosan.cz, a zkontroluj, že je banner pryč

feat: remove ukraine banner

---

.github/workflows/dependabot.yml

- bezpečnostní aktualizace se automaticky nainstalují (a nasadí) pokud je změna v patch verzi semantického verzování

feat: automerge patch updates by dependabot

---

.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

- commity se nyní kontorlují, jestli splňují conventionalcommits pravidla

Přidán commit linter

---

interni/package-lock.json
interni/package.json
interni/src/app/modules/events/views/events-view/events-view-accounting/events-view-accounting.component.ts
interni/src/app/modules/events/views/events-view/events-view-attendees/events-view-attendees.component.html
interni/src/app/modules/events/views/events-view/events-view-attendees/events-view-attendees.component.ts
interni/src/app/modules/events/views/events-view/events-view.component.html
server/src/controllers/events-event-accounting.js

- čísla pro účtenky se nyní navrhují od jedničky ne od dvojky
- správné řazení účtenek s číslem 10 a výš
- vedoucí akce se nyní zobrazují v seznamu účastníků 
1. Otevři si interni.test.bosan.cz, a zkontroluj, že verze je `3.2.7`. Pokud není, obnov stránku a zkontroluj menu pro aktualizaci.
2. Zkontroluj, jestli jsou opraveny chyby výše

Opravy v účtování

---

web/src/app/views/camp-view/camp-view.component.html

- Informace k táborům 2023
1. Otevři si [test.bosan.cz/tabor](https://test.bosan.cz/tabor)
2. Zkontroluj, že jsou informace k táborům správné.

Informace k táborům 2023

---

web/src/app/views/camp-view/camp-view.component.html

Follow up to #539.
Viz diff, primitivní.
1. Otevři si interni.test.bosan.cz, a zkontroluj, že verze je `X.X.X`. Pokud není, obnov stránku a zkontroluj menu pro aktualizaci.
2.

Doplnění chybějících změn roku u táboru

---

web/CONTRIBUTING.md

Byl dost neaktuální a podle mě byl místy špatně pochopitelný, tak jsem ho trošku zrevidoval, dokud mám ještě v živé paměti, co mi na něm nesedělo.

Update návodu na editování webu

---

web/src/app/views/about-view/about-view.component.html
web/src/app/views/events-view/events-view.component.html

Aktualizované info u bazénu, kanálu a kajakářské školičky, výměna názvu loděnice u schůzek v O nás, změna vykání na tykání v Kdo jsme (pokud jsem dobře vyrozměl, tak je shoda spíš na tom všude tykat).
- 
1. Otevři si test.bosan.cz.
2. Zkoukni, jestli jsou ty změny takto optimální

Info u bazénu a další drobné změny

---

web/src/app/views/camp-view/camp-view.component.html

- update summer camp leaders mailto links
1. Otevři si test.bosan.cz na kartě tábor.
2. Klikni na mailovou adresu hlavního vedoucího tábora a ověř, že příjemce případného mailu je vyplněný správně.

fix: update summer camp leaders mailto links (#560)

---

web/src/app/components/page-footer/page-footer.component.html

- Přidán CompuNet do sponzorů, Kudyznudy.cz zobrazeno jako text
2. Zkontroluj, že mezi sponzory jsou CompuNet a Kudyznudy a odkazy vedou tam kam maji

feat: update sponsors section

---

web/src/environments/environment.dev-test.ts
web/src/environments/environment.test.ts

- mělo by fungovat API na tetsu
2. Zkontroluj, že funguje API na testu

fix: test api urls

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-test.yml

fix: bad watchtower url

---

web/src/app/views/events-view/events-view.component.html

- nový link na přihlašování na tréningy na K (ten starý přestal fungovat)
2. Zkontroluj, že …

fix:link-to-K-training-form

---

web/src/app/views/about-view/about-view.component.html

- doplnění členského příspěvku (požadavek ze strany MHMP pro splnění podmínek městských grantů, ostatně i rodiče by to mohlo zajímat :))
- navíc link na mapy.cz
- drobná zjednodušující textová úprava
2. Zkontroluj, že na úvodní stránce najdeš informaci o členském příspěvku. Podobně jako

fix: added membership fee

---

web/src/app/views/about-view/about-view.component.html

viz https://github.com/bosancz/bosan.cz/pull/596#discussion_r1823825132
- 
2. Zkontroluj, že … se nic nezměnilo. :)

fix: use &hellip;

---

web/src/app/views/camp-view/camp-view.component.html

- update data táborů
- update hlavních vedoucích
- přidání slevy za dar W4W
2. Zkontroluj, že
- data táborů sedí s přihláškami
- hlavní vedoucí táborů jsou správně a kontakty na ně jsou správně
- oddíly na táborech jsou správně
- text a struktura slevy za dar dává smysl

Tábory 2025

---

web/src/app/views/camp-view/camp-view.component.html

- drobný fix poznámky pro dary W4W
2. Zkontroluj, že znění je "Ostrov Šán - variabilní symbol"

fix: remark for donations
